name: test-py38-functional-devstack

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v4

      - name: Install Devstack and Keycloak
        run: |
          ./ci/devstack.sh

      - name: Install ColdFront and plugin
        run: |
          ./ci/setup.sh

      - name: Run functional tests
        run: |
          ./ci/run_functional_tests_openstack.sh
