name: test-unit

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        python-version: [3.9, 3.12]
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install ColdFront and plugin
        run: |
          ./ci/setup.sh

      - name: Run unit tests
        run: |
          ./ci/run_unit_tests.sh
