name: test-py39-functional

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: 3.9

      - name: Install ColdFront and plugin
        run: |
          python -m pip install --upgrade pip
          pip install -r test-requirements.txt
          pip install -e .

      - name: Install and start Ceph RadosGW
        run: |
          sudo ./ci/radosgw.sh

      - name: Install and start Microstack
        run: |
          ./ci/microstack.sh

      - name: Run functional tests
        run: |
          export DJANGO_SETTINGS_MODULE="local_settings"
          export FUNCTIONAL_TESTS="True"
          export CREDENTIAL_NAME=$(openssl rand -base64 12)
          export OPENSTACK_DEVSTACK_APPLICATION_CREDENTIAL_SECRET=$(
              microstack.openstack application credential create "$CREDENTIAL_NAME" -f value -c secret)
          export OPENSTACK_DEVSTACK_APPLICATION_CREDENTIAL_ID=$(
              microstack.openstack application credential show "$CREDENTIAL_NAME" -f value -c id)
          export OPENSTACK_PUBLIC_NETWORK_ID=$(microstack.openstack network show external -f value -c id)
          export OS_AUTH_URL="https://localhost:5000"

          coldfront test coldfront_plugin_cloud.tests.functional.openstack
