name: test-py39-unit

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: 3.9

      - name: Install ColdFront and plugin
        run: |
          ./ci/setup.sh

      - name: Run unit tests
        run: |
          ./ci/run_unit_tests.sh
